/* CREATE A NEW DATABASE */
CREATE DATABASE PROJETO;

/* CONNECT IN TO DATABASE */
USE PROJETO;

/* CREATE A NEW TABLE IN TO DATABASE */
CREATE TABLE CLIENTE(
  NOME VARCHAR(30),
  SEXO CHAR(1),
  EMAIL VARCHAR(30),
  CPF INT(11),
  TELEFONE VARCHAR(30),
  ENDERECO VARCHAR (100)
);

/* SHOW TABLES */
SHOW TABLES;

/* SHOW ESTRUCTURE OF A TABLE */
DESC CLIENTE;

/* FILLING IN A TABLE (OMITING THE COLUMNS) PT 1*/
INSERT INTO CLIENTE VALUES('RENAN', 'M', 'RENAN@GMAIL.COM', 98765432100, '21968701055', 'RUA LEOPOLDO 411/201');

INSERT INTO CLIENTE VALUES('NOMENULL', 'M', NULL, 00123456789, '2199999999', 'RUA MASSA 11');

/* FILLING IN A TABLE (INSERTING THE COLUMNS) PT 2*/
INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541421456, '25078869', 'RIACHUELO - CENTRO');

INSERT INTO CLIENTE(NOME, SEXO, CPF, TELEFONE, ENDERECO) VALUES('ANA', 'F', 85548962, '545478869', 'TIJUCA');

/* SELECTS */
SELECT NOW();

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'RENAN' AS STUDENT;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT * FROM CLIENTE;

/* SELECTS WITH FILTERS */
SELECT NOME, SEXO FROM CLIENTE WHERE SEXO = 'M';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE 'RUA%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%RUA';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE ENDERECO LIKE '%JUCA%';
