-- INSERT INTO CLIENTE VALUES('MARCOS','M',NULL,885755896,'58748895','TIJUCA - RJ');

-- FILTRAR VALOR NULL
SELECT NOME, SEXO, EMAIL, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, EMAIL, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;