CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
  NOME_DO_LIVRO VARCHAR(30),
  NOME_DO_AUTOR VARCHAR(30),
  SEXO_DO_AUTOR CHAR(1),
  NUMERO_DE_PAGINAS VARCHAR(10),
  NOME_DA_EDITORA VARCHAR(30),
  VALOR_DO_LIVRO FLOAT(7, 2),
  UF CHAR(2),
  ANO CHAR(4)
);

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 01', 'AUTOR 01', 'M', '100', 'ATLAS', 49.9, 'RJ', '1997');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 02', 'AUTOR 02', 'M', '200', 'ATLAS', 50, 'RJ', '1998');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 03', 'AUTOR 03', 'M', '300', 'ATLAS', 49.99, 'RJ', '1999');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 04', 'AUTOR 04', 'M', '400', 'ATLAS', 30, 'RJ', '2000');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 05', 'AUTOR 05', 'M', '500', 'ATLAS', 37.41, 'RJ', '2001');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 06', 'AUTOR 06', 'M', '600', 'ATLAS', 35.49, 'RJ', '2002');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 07', 'AUTOR 07', 'M', '700', 'ATLAS', 35.420, 'RJ', '2003');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 08', 'AUTOR 08', 'F', '800', 'ATLAS', 35.420, 'RJ', '2004');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 09', 'AUTOR 09', 'M', '900', 'ATLAS', 35.420, 'SP', '2004');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 10', 'AUTOR 10', 'M', '1000', 'ATLAS', 35.420, 'PR', '2005');

INSERT 
INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO)
VALUES('LIVRO 11', 'AUTOR 11', 'F', '1100', 'ATLAS', 35.420, 'PR', '2006');

/* TRAZER TODOS OS DADOS */
SELECT * FROM LIVROS;

/* TRAZER O NOME DO LIVRO E O NOME DA EDITORA */
SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/* TRAZER O NOME DO LIVRO PUBLICADOS PELO SEXO MASCULINO */
SELECT NOME_DO_LIVRO FROM LIVROS WHERE SEXO_DO_AUTOR = 'M';

/* TRAZER NOME DO LIVRO E NUMERO DE PAGINAS  SEXO FEMININO */
SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS WHERE SEXO_DO_AUTOR = 'F';

/* TRAZER OS DADOS DO SEXO MASCULINO QUE SÃO DO ESTADO RJ OU SP */
SELECT NOME_DO_AUTOR, SEXO_DO_AUTOR FROM LIVROS WHERE UF = 'SP' OR UF = 'PR' AND SEXO_DO_AUTOR = 'M';
/*CORREÇÃO*/
SELECT NOME_DO_AUTOR, SEXO_DO_AUTOR 
FROM LIVROS 
WHERE SEXO_DO_AUTOR = 'M'
AND (UF = 'SP' OR UF = 'PR');