/* PRIMEIRA FORMA NORMAL */

/*
  1º TODO CAMPO VETORIZADO, SE TORNARÁ OUTRA TABELA
  EX: 
    [AMARELO, AZUL, LARANJA, VERDE] -> CORES
    [KA, FIESTA, UNO, CIVIC] -> CARROS

  2º TODO CAMPO MULTIVALORADO, SE TORNARÁ OUTRA TABELA.
    - QUANDO O CAMPO FOR DIVISÍVEL.
  EX: 
    LEOPOLDO - ANDARAI - RIO DE JANEIRO - RJ
    |  RUA  |   BAIRRO |   CIDADE   |  ESTADO

  3º TODO CAMPO NECESSITA DE PELO MENOS UM CAMPO ÚNICO (CHAVE PRIMARIA - "PRIMARY KEY")('UUID')
    - CHAVE NATURAL = CPF (NÃO UTILIZAR COMO PK)
    - ARTIFICIAL = CRIADA (USADA PARA PK) - (CRIADA COLUNA ID)

*/

CREATE DATABASE COMERCIO;