CREATE DATABASE COMERCIO;

USE DATABASE COMERCIO;


/* TABELA CLIENTE */
CREATE TABLE CLIENTE(
  IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  SEXO ENUM('M','F') NOT NULL, -- ENUM SÓ VAI PERMITIR UM DESSES VALORES.
  EMAIL VARCHAR(50) UNIQUE,
  CPF VARCHAR(15) UNIQUE
);