SELECT * FROM CLIENTE;

DELETE FROM CLIENTE; -- DANGERRRR!! DELETARÁ TUDO!

SELECT COUNT(*)
FROM CLIENTE;  -- TOTAL: 5

SELECT COUNT(*)
FROM CLIENTE
WHERE NOME = 'MARIA'; -- 2

DELETE FROM CLIENTE
WHERE NOME = 'MARIA'; -- DELETE: 2, TOTAL: 3

INSERT INTO CLIENTE VALUES('CARLA', 'F', 'C.LOPES@GMAIL.COM', 123456, '21 90000', 'RUA COPPER LEAFR - KITCHENER');

INSERT INTO CLIENTE VALUES('CARLA', 'F', 'PEDRO@GMAIL.COM', 123456, '21 90000', 'RUA COPPER LEAFR - KITCHENER');

 CARLA   | F    | C.LOPES@GMAIL.COM |     123456 | 21 90000    | RUA COPPER LEAFR - KITCHENER
 CARLA   | F    | PEDRO@GMAIL.COM   |     123456 | 21 90000    | RUA COPPER LEAFR - KITCHENER

-- PARA DELETAR COM SEGURANÇA A CARLA COM E-MAIL PEDRO, VOCÊ FAZ UM SELECT PARA ACHAR AQUELE REGISTRO EM ESPECÍFICO.

-- ERRADO ❌, OR DELETARIA ATÉ OS COM TELEFONE ALI
SELECT * FROM CLIENTE
WHERE NOME = 'CARLA'
OR TELEFONE = '21968701055';

-- CORRETO ✅ -> ESSA POSSO DELETAR :
SELECT * FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'PEDRO@GMAIL.COM';

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'PEDRO@GMAIL.COM';

  nome   | sexo |       email       |    cpf     |  telefone   |           endereco           
---------+------+-------------------+------------+-------------+------------------------------
 JOÃO    | M    | JOAO@GMAIL.COM    |     123456 | 21968701055 | MAIA LACERDA ESTACIO - RJ
 OSCAR   | M    | OSCAR@GMAIL.COM   |     123456 | 21968701055 | OSCAR CURY - RJ
 PEDRO 3 | M    | PEDRO3@GMAIL.COM  | 2147483647 | 21968701055 | MAIA LACERDA ESTACIO - RJ
 CARLA   | F    | C.LOPES@GMAIL.COM |     123456 | 21 90000    | RUA COPPER LEAFR - KITCHENER  nome   | sexo |       email       |    cpf     |  telefone   |           endereco           
---------+------+-------------------+------------+-------------+------------------------------
 JOÃO    | M    | JOAO@GMAIL.COM    |     123456 | 21968701055 | MAIA LACERDA ESTACIO - RJ
 OSCAR   | M    | OSCAR@GMAIL.COM   |     123456 | 21968701055 | OSCAR CURY - RJ
 PEDRO 3 | M    | PEDRO3@GMAIL.COM  | 2147483647 | 21968701055 | MAIA LACERDA ESTACIO - RJ
 CARLA   | F    | C.LOPES@GMAIL.COM |     123456 | 21 90000    | RUA COPPER LEAFR - KITCHENER


