/* TEM EM TODOS DB */
SELECT NOW();

SELECT NOW() as DATA_HORA;

SELECT NOW() as DATA_HORA, 'RENAN' as STUDENT;

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME as CLIENTE, SEXO, EMAIL FROM CLIENTE;


/*APENAS PARA FINS ACADEMICOS*/

SELECT * FROM CLIENTE;
SELECT cliente.* FROM CLIENTE;

SELECT * FROM CLIENTE, NOW() AS DATA_HORA;
