/*DDL -> DATA DEFINITION LANGUAGE */

CREATE TABLE IF NOT EXISTS PRODUTO(
  IDPRODUTO SERIAL PRIMARY KEY,
  NOME_PRODUTO VARCHAR(30) NOT NULL,
  PRECO INTEGER,
  FRETE NUMERIC(10, 2)
);

CREATE DATABASE DLL;

\c dll;

-- MYSQL
ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INTEGER NOT NULL;

-- PSQL 1
ALTER TABLE PRODUTO
RENAME COLUMN PRECO TO VALOR_UNITARIO;
-- PSQL 2
ALTER TABLE PRODUTO
ALTER COLUMN VALOR_UNITARIO SET NOT NULL;

/* MODIFY ALTERANDO TIPO */
-- mysql
ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

ALTER TABLE PRODUTO
ADD PESO NUMERIC(10, 2) NOT NULL;

SELECT PESO, FRETE FROM PRODUTO;


ALTER TABLE PRODUTO
DROP COLUMN PESO;

-- MYSQL
ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT(10,2) NOT NULL
FIRST NOME_PRODUTO;