SELECT NOME, EMAIL
FROM CLIENTE;

-- UPDATE
UPDATE CLIENTE
SET EMAIL = 'JORGE@GMAIL.COM'
WHERE NOME = 'JORGE';

-- DELETE FROM CLIENTE (PERIGOSO, [LIMPA A TABELA])
-- DELETE DEVE SER USADO COM COUNT E WHERE (MAIS SEGURO POSSÍVEL)

SELECT COUNT(*)
FROM
CLIENTE; -- 6

SELECT COUNT(*)
FROM CLIENTE
WHERE NOME = "ANA";

DELETE FROM CLIENTE
WHERE NOME = "ANA";

SELECT COUNT(*)
FROM
CLIENTE; -- 5

SELECT  * FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@GMAIL.COM';

DELETE FROM CLIENTE
WHERE NOME = 'CARLA'
AND EMAIL = 'LILIAN@GMAIL.COM';