/*
  CATEGORIAS

  DML -> DATA MANIPULATION LANGUAGE
  DDL -> DATA DEFINITION LANGUAGE
  DCL -> DATA CONTROL LANGUAGE
  TCL -> TRANSACTION CONTROL LANUAGE
*/


-- -> DML
-- INSERTS
INSERT INTO CLIENTE VALUES(DEFAULT, 'PAULA', 'F', 'PAULA@GMAIL.COM', '98761323');
INSERT INTO CLIENTE VALUES(DEFAULT, 'TEJANDO', 'M', 'TEJANDO@GMAIL.COM', '123987654');
INSERT INTO ENDERECO VALUES(DEFAULT, 'JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 8);

-- FILTROS 
SELECT * FROM CLIENTE
WHERE SEXO = 'M';



-- UPDATE e DELETE

--1) VERIFIQUE!!!!!!!!!!!!!!!!!!
SELECT * FROM CLIENTE
WHERE id_cliente = 8;

UPDATE CLIENTE
SET email = 'tejando@yahoo.com.br'
WHERE id_cliente = 8;


-- DELETE
SELECT * FROM CLIENTE
WHERE id_cliente = 6;

DELETE FROM CLIENTE
WHERE id_cliente = 6;
