\c projeto;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL = NULL; -- não retorna nada, a sintaxe correta é:

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

-- JÁ AO CONTRÁRIO, PARA TRAZER OS QUE NÃO SÃO NULL
SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;